### ISSUE TITLE
namespace collisions

### ISSUE THREAD

**Issue by dereuromark** [SocialPlexus/users#1]
I am a bit worried about the too generic namespaces per plugin:
https://github.com/SocialPlexus/users/blob/master/composer.json#L42

Maybe they should be prefixed with  `SocialPlexus/` namespace.

E.g. with your "Feed" one, if you would ever want to use the generic [Feed](https://github.com/dereuromark/cakephp-feed) plugin in your app, it would then be possible.
Those two shouldnt eliminate it eather, as they might both come in handy - by using a less conflicting namespace for all the SP plugins you will make it easier in the future to combine plugins.

**Comment by Theaxiom** [comment]
Thanks @dereuromark -- I will definitely fix that.
